[platformio]
src_dir = Core/Src
include_dir = Core/Inc

[env:nucleo_f401re]
platform = ststm32
board = nucleo_f401re
framework = stm32cube

; ST-Link upload via USB
upload_protocol = stlink

; Serial monitor settings (USART2 over ST-Link VCP)
monitor_speed = 115200

; Enable floating point support in printf/snprintf (newlib-nano)
build_flags = -Wl,-u,_printf_float
